#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

function sets_framework_cmsmadesimple() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "cmsmadesimple" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if sets_framework_cmsmadesimple; then
            echo "-----> Detected cmsmadesimple app"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Setting up cmsmadesimple app"
        #cp "$basedir/../conf/nginx/cmsmadesimple.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        /bin/mkdir -p $basedir/web/tmp/cache
        /bin/mkdir -p $basedir/web/tmp/configs
        /bin/mkdir -p $basedir/web/tmp/template_c
        /bin/chmod 777 -R $basedir/web/tmp
        /bin/touch $basedir/web/tmp/cache/index.html
        /bin/touch $basedir/web/tmp/configs/index.html
        /bin/touch $basedir/web/tmp/template_c/index.html
        ;;
esac
